version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=tezos_delegations
      - TZKT_API_BASE_URL=https://api.ghostnet.tzkt.io/v1/

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tezos_delegations
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: